# Generated by Django 2.0 on 2018-02-05 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testwebapp', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_data',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
