# Generated by Django 2.0 on 2018-02-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testwebapp', '0003_users_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_data',
            name='date',
            field=models.CharField(max_length=25),
        ),
    ]
